# Include default parameters of your algorithm here.

mixedprec: True
backbone: resnet50
learning_rate: 2e-1
optimizer: SGD
gamma: 0.1
milestones:
  - 30
  - 60
  - 90
momentum: 0.9
weight_decay: 1e-4
