# Include default parameters of your algorithm here.

mixedprec: True
backbone: resnet50 # Net for MNIST
optimizer: SGD
learning_rate: 1e-4
milestones:
  - 30
  - 60
  - 90
momentum: 0.9
weight_decay: 1e-4
gamma: 0.1
